FROM arm32v6/python:3.9.7-alpine

RUN apk add --update docker openrc screen

WORKDIR /usr/src/app
COPY requirements-arm32v6.txt ./
RUN pip install --no-cache-dir -r requirements-arm32v6.txt
COPY . .
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5000"]